# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manuscript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=2)),
                ('town', models.CharField(max_length=50)),
                ('library', models.CharField(max_length=100)),
                ('shelfmark', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=30)),
                ('olim', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=50)),
                ('material', models.CharField(max_length=50)),
                ('width', models.CharField(max_length=50)),
                ('height', models.CharField(max_length=50)),
                ('folios', models.CharField(max_length=20)),
                ('inspection', models.CharField(max_length=20)),
                ('literature', models.TextField()),
                ('reproduction', models.CharField(max_length=100)),
                ('content', models.ManyToManyField(to='manuscripts.Text')),
            ],
        ),
    ]
