# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-15 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0001_squashed_0026_auto_20160409_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reproduction',
            name='coverage',
            field=models.CharField(blank=True, choices=[('partial', 'Partial'), ('complete', 'Complete')], max_length=15),
        ),
    ]
