# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-29 13:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commentaries', '0003_auto_20160329_1509'),
        ('manuscripts', '0001_initial'),
    ]

    operations = [
    ]
