# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-29 13:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commentaries', '0004_auto_20160329_1515'),
        ('manuscripts', '0002_manuscriptcontentcommentary'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManuscriptContentCommentary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('folios', models.CharField(blank=True, max_length=500, null=True)),
                ('note', models.CharField(blank=True, max_length=500, null=True)),
                ('content', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='commentaries.Commentary')),
                ('manuscript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manuscripts.Manuscript')),
            ],
            options={
                'verbose_name': 'Manuscript content (commentary)',
                'verbose_name_plural': 'Manuscript content (commentaries)',
            },
        ),
    ]
