# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 12:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0002_manuscript'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManuscriptContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folios', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='text',
            name='source',
            field=models.ManyToManyField(to='manuscripts.Manuscript'),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='content',
            field=models.ManyToManyField(blank=True, to='manuscripts.Text'),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='date',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='folios',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='height',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='inspection',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='literature',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='material',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='number',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='olim',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='reproduction',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='shelfmark',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='width',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='manuscriptcontent',
            name='manuscript',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manuscripts.Manuscript'),
        ),
        migrations.AddField(
            model_name='manuscriptcontent',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manuscripts.Text'),
        ),
    ]
