# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-15 18:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0002_auto_20160415_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manuscriptcontentcommentary',
            name='content',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='commentaries.Text'),
        ),
    ]
