# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0003_auto_20160415_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manuscript',
            name='material',
            field=models.CharField(blank=True, choices=[('parcment', 'Parchment'), ('paper', 'Paper'), ('combi', 'Parch. and pap.')], max_length=50, null=True),
        ),
    ]
