# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 13:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0003_auto_20151229_1254'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('town_name', models.CharField(max_length=255)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manuscripts.Country')),
            ],
        ),
        migrations.RemoveField(
            model_name='manuscript',
            name='country',
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='library',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='town', chained_model_field='town_name', on_delete=django.db.models.deletion.CASCADE, show_all=True, to='manuscripts.Town'),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='town',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alter', to='manuscripts.Town'),
        ),
        migrations.AlterField(
            model_name='text',
            name='source',
            field=models.ManyToManyField(blank=True, to='manuscripts.Manuscript'),
        ),
    ]
