# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-01 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0003_manuscriptcontentcommentary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manuscriptinspection',
            name='inspection_type',
            field=models.CharField(choices=[('digital', 'Digital reproduction'), ('situ', 'In situ'), ('microfilm', 'Microfilm')], max_length=10),
        ),
    ]
