# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-05 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0004_auto_20160401_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='reproduction',
            name='note',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='reproduction',
            name='reproduction_coverage',
            field=models.IntegerField(blank=True, choices=[(1, 'Partial'), (2, 'Complete')], null=True),
        ),
    ]
