# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 07:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0004_auto_20160426_0902'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReproductionWishlish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('wish', models.BooleanField()),
                ('folio_range', models.CharField(blank=True, max_length=100, null=True)),
                ('note', models.CharField(blank=True, max_length=500, null=True)),
                ('manuscript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manuscripts.Manuscript')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
