# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 13:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0004_auto_20151229_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manuscriptcontent',
            name='manuscript',
        ),
        migrations.RemoveField(
            model_name='manuscriptcontent',
            name='title',
        ),
        migrations.RenameField(
            model_name='country',
            old_name='county_name',
            new_name='county',
        ),
        migrations.DeleteModel(
            name='ManuscriptContent',
        ),
    ]
