# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-06 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0005_auto_20160405_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reproduction',
            name='media',
            field=models.CharField(blank=True, choices=[('digital', 'Digital'), ('microfilm', 'Micro film')], max_length=100),
        ),
    ]
