# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 07:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0005_reproductionwishlish'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReproductionWishlish',
            new_name='ReproductionWishlist',
        ),
    ]
