# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 07:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0006_auto_20160426_0913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reproductionwishlist',
            name='wish',
        ),
    ]
