# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 13:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0006_auto_20151229_1354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='county_name',
            new_name='country_name',
        ),
    ]
