# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 14:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0008_auto_20151229_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('library_name', models.CharField(max_length=255)),
                ('library_town', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manuscripts.Town')),
            ],
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='library',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='town', chained_model_field='town_name', on_delete=django.db.models.deletion.CASCADE, related_name='library', show_all=True, to='manuscripts.Library'),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='town',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='country', chained_model_field='country', on_delete=django.db.models.deletion.CASCADE, related_name='town', show_all=True, to='manuscripts.Town'),
        ),
    ]
