# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-06 08:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0008_auto_20160406_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reproduction',
            name='archive',
            field=models.ForeignKey(blank=True, max_length=255, on_delete=django.db.models.deletion.CASCADE, to='repositories.Archive'),
        ),
        migrations.AlterField(
            model_name='reproduction',
            name='media',
            field=models.CharField(blank=True, choices=[('digital', 'Digital'), ('microfilm', 'Micro film')], max_length=100),
        ),
    ]
