# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 09:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0009_auto_20151229_1408'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspector', models.CharField(max_length=255)),
                ('inspection_type', models.CharField(choices=[('digital', 'Digital reproduction'), ('situ', 'In situ')], max_length=10)),
                ('inspection_date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='manuscript',
            name='inspection',
        ),
        migrations.RemoveField(
            model_name='manuscript',
            name='reproduction',
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='library',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='town', chained_model_field='library_town', on_delete=django.db.models.deletion.CASCADE, related_name='library', show_all=True, to='manuscripts.Library'),
        ),
        migrations.AddField(
            model_name='manuscript',
            name='inspections',
            field=models.ManyToManyField(blank=True, to='manuscripts.Inspection'),
        ),
    ]
