# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 11:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0010_auto_20151230_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manuscript',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manuscripts.Country'),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='material',
            field=models.CharField(blank=True, choices=[('parcment', 'Parchment'), ('paper', 'Paper')], max_length=50),
        ),
    ]
