# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-06 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0011_auto_20160406_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reproduction',
            name='reproduction_coverage',
            field=models.IntegerField(blank=True, choices=[(1, 'Partial'), (2, 'Complete')], default=False, null=True),
        ),
    ]
