# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0011_auto_20151230_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='manuscript',
            name='period',
            field=models.CharField(blank=True, choices=[('13.2', '1226-1250'), ('13.3', '1250-1275'), ('13.4', '1276-1300'), ('14.1', '1301-1325'), ('14.2', '1326-1350'), ('14.3', '1351-1375'), ('14.4', '1376-1400'), ('15.1', '1401-1425'), ('15.2', '1426-1450')], max_length=100),
        ),
    ]
