# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0012_manuscript_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='manuscript',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
