# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 12:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0013_manuscript_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reproductions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archive', models.CharField(max_length=255)),
                ('media', models.CharField(choices=[('digital', 'Digital'), ('microfilm', 'Micro film')], max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='manuscript',
            name='reproduction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manuscripts.Reproductions'),
        ),
    ]
