# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0015_auto_20151230_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='reproductions',
            name='number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
