# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 12:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0016_reproductions_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manuscript',
            old_name='reproduction',
            new_name='reproductions',
        ),
    ]
