# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 12:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0017_auto_20151230_1322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reproductions',
            old_name='number',
            new_name='reference',
        ),
    ]
