# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0018_auto_20151230_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='reproductions',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
