# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-06 08:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0018_auto_20160406_1020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reproduction',
            name='reproduction_coverage',
        ),
    ]
