# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0019_reproductions_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='manuscript',
            name='dimension_note',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Note about dimensions'),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='height',
            field=models.FloatField(blank=True, verbose_name='Height (in mm.)'),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='width',
            field=models.FloatField(blank=True, verbose_name='Width (in mm.)'),
        ),
    ]
