# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-06 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0019_remove_reproduction_reproduction_coverage'),
    ]

    operations = [
        migrations.AddField(
            model_name='reproduction',
            name='reproduction_coverage',
            field=models.CharField(blank=True, choices=[('partial', 'Partial'), ('complete', 'Complete')], max_length=15, null=True),
        ),
    ]
