# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0020_auto_20151230_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='manuscript',
            name='layout',
            field=models.TextField(blank=True, null=True),
        ),
    ]
