# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-06 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0020_reproduction_reproduction_coverage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reproduction',
            name='reproduction_coverage',
            field=models.CharField(choices=[('partial', 'Partial'), ('complete', 'Complete')], max_length=15, null=True),
        ),
    ]
