# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 15:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0021_manuscript_layout'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reproductions',
            new_name='Reproduction',
        ),
    ]
