# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-06 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0021_auto_20160406_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reproduction',
            name='reproduction_coverage',
            field=models.CharField(blank=True, choices=[('partial', 'Partial'), ('complete', 'Complete')], default='', max_length=15),
            preserve_default=False,
        ),
    ]
