# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-06 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0022_auto_20160406_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='reproduction',
            name='note',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
