# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 17:08
from __future__ import unicode_literals

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0022_auto_20151230_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='country_name',
        ),
        migrations.AddField(
            model_name='country',
            name='country',
            field=django_countries.fields.CountryField(default='GB', max_length=2),
        ),
    ]
