# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 17:10
from __future__ import unicode_literals

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0023_auto_20151230_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
