# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-06 08:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0023_reproduction_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reproduction',
            old_name='reproduction_coverage',
            new_name='coverage',
        ),
    ]
