# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-09 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0024_auto_20160406_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='manuscriptcontentcommentary',
            name='explicit',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manuscriptcontentcommentary',
            name='incipit',
            field=models.TextField(blank=True, null=True),
        ),
    ]
