# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-09 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0025_auto_20160409_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manuscriptcontentcommentary',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
