# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0026_manuscript_catalogue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manuscript',
            name='height',
            field=models.FloatField(blank=True, null=True, verbose_name='Height (in mm.)'),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='width',
            field=models.FloatField(blank=True, null=True, verbose_name='Width (in mm.)'),
        ),
    ]
