# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 17:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0027_auto_20151230_1831'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogueUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('manuscript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manuscripts.Manuscript')),
            ],
        ),
        migrations.AddField(
            model_name='manuscript',
            name='catalogue_url',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catalogue_url', to='manuscripts.CatalogueUrl'),
        ),
    ]
