# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 17:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0028_auto_20151230_1844'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CatalogueUrl',
            new_name='OnlineMaterial',
        ),
        migrations.RemoveField(
            model_name='manuscript',
            name='catalogue_url',
        ),
    ]
