# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0029_auto_20151230_1850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manuscript',
            name='period',
        ),
        migrations.AddField(
            model_name='manuscript',
            name='date_earliest',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='manuscript',
            name='date_latest',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
