# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0030_auto_20151230_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='title_addon',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title addon'),
        ),
        migrations.AlterField(
            model_name='text',
            name='date',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
