# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 18:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0031_auto_20151230_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='translator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translator', to='manuscripts.Author'),
        ),
    ]
