# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 18:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0032_text_translator'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManuscriptContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manuscripts.Text')),
                ('manuscript', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manuscripts.Manuscript')),
            ],
        ),
    ]
