# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0033_manuscriptcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='manuscriptcontent',
            name='folios',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
