# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0035_remove_manuscript_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='manuscriptcontent',
            name='note',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
