# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0036_manuscriptcontent_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manuscriptcontent',
            name='folios',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
