# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0037_auto_20151230_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='date',
        ),
        migrations.AddField(
            model_name='author',
            name='birth',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='death',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
