# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 19:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0039_manuscriptinspection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manuscript',
            name='inspections',
        ),
        migrations.DeleteModel(
            name='Inspection',
        ),
    ]
