# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 19:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0040_auto_20151230_2029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manuscript',
            name='catalogue',
        ),
    ]
