# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0042_auto_20151230_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='explicit',
            field=models.TextField(blank=True, max_length=1020, null=True),
        ),
        migrations.AddField(
            model_name='text',
            name='incipit',
            field=models.TextField(blank=True, max_length=1020, null=True),
        ),
    ]
