# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 10:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0043_auto_20151230_2101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reproduction',
            old_name='reference',
            new_name='referencenumber',
        ),
    ]
