# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0044_auto_20160102_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
