# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0045_text_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='floruit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
