# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0047_remove_text_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='literature',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='text',
            name='literature',
            field=models.TextField(blank=True, null=True),
        ),
    ]
