# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 16:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0049_author_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manuscript',
            name='date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='folios',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='literature',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='material',
            field=models.CharField(blank=True, choices=[('parcment', 'Parchment'), ('paper', 'Paper')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='olim',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='shelfmark',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='onlinematerial',
            name='manuscript',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manuscripts.Manuscript'),
        ),
        migrations.AlterField(
            model_name='onlinematerial',
            name='url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='text',
            name='date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
