# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-03 09:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0050_auto_20160102_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manuscripts.Country'),
        ),
        migrations.AlterField(
            model_name='archive',
            name='town',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='country', chained_model_field='country', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='archive_town', show_all=True, to='manuscripts.Town'),
        ),
    ]
