# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-03 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0051_auto_20160103_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='authorship',
            field=models.IntegerField(blank=True, choices=[('5', 'Certain'), ('4', 'Possible'), ('3', 'Disputed'), ('2', 'Dubious'), ('1', 'Untrue')], null=True),
        ),
    ]
