# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-03 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0052_text_authorship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='authorship',
            field=models.CharField(blank=True, choices=[('certain', 'Certain'), ('possible', 'Possible'), ('disputed', 'Disputed'), ('dubious', 'Dubious'), ('untrue', 'Untrue')], max_length=10, null=True),
        ),
    ]
