# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-05 13:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0053_auto_20160103_2218'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentaryType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentary_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='text',
            name='commentary_on',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manuscripts.Text'),
        ),
        migrations.AddField(
            model_name='text',
            name='commentary_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manuscripts.CommentaryType'),
        ),
    ]
