# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-05 13:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0054_auto_20160105_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentedOn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='text',
            name='commentary_on',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manuscripts.CommentedOn'),
        ),
        migrations.AddField(
            model_name='commentedon',
            name='commented_on',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manuscripts.Text'),
        ),
    ]
