# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-05 13:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0055_auto_20160105_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentedon',
            name='commented_on',
        ),
        migrations.AddField(
            model_name='text',
            name='commented_on',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='text',
            name='commentary_on',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manuscripts.Text'),
        ),
        migrations.DeleteModel(
            name='CommentedOn',
        ),
    ]
