# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-05 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0056_auto_20160105_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='mora_reference',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
