# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-05 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0057_text_mora_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='author_role',
            field=models.IntegerField(blank=True, choices=[(1, 'Commentator'), (2, 'Authority'), (3, 'Translator')], null=True),
        ),
        migrations.AlterField(
            model_name='text',
            name='mora_reference',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
