# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-05 19:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0060_auto_20160105_2051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentary',
            old_name='author',
            new_name='commentator',
        ),
    ]
