# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-05 19:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0061_auto_20160105_2054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='author_role',
        ),
    ]
