# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-05 20:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0062_remove_author_author_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentary',
            name='commented_on',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='commentary',
            name='translator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commentary_translator', to='manuscripts.Author'),
        ),
        migrations.AlterField(
            model_name='commentary',
            name='commentator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manuscripts.Author'),
        ),
    ]
