# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-05 20:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0063_auto_20160105_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentary',
            name='translator',
        ),
    ]
