# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-05 20:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0064_remove_commentary_translator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentary',
            name='commented_on',
        ),
        migrations.AlterField(
            model_name='commentary',
            name='commentator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manuscripts.Commentator'),
        ),
    ]
