# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-05 21:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0068_auto_20160105_2207'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorityText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('title_addon', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title addon')),
                ('date', models.CharField(blank=True, max_length=50, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('literature', models.TextField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manuscripts.Authority')),
                ('translator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translator', to='manuscripts.Translator')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='text',
            name='author',
        ),
        migrations.RemoveField(
            model_name='text',
            name='commentary_on',
        ),
        migrations.RemoveField(
            model_name='text',
            name='commentary_type',
        ),
        migrations.RemoveField(
            model_name='text',
            name='translator',
        ),
        migrations.AlterField(
            model_name='commentary',
            name='commentary_on',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manuscripts.AuthorityText'),
        ),
        migrations.DeleteModel(
            name='Text',
        ),
    ]
