# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-06 15:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0069_auto_20160105_2215'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('title_addon', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title addon')),
                ('date', models.CharField(blank=True, max_length=50, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('literature', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ManuscriptContent2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folios', models.CharField(blank=True, max_length=20, null=True)),
                ('note', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='authoritytext',
            name='author',
        ),
        migrations.RemoveField(
            model_name='authoritytext',
            name='translator',
        ),
        migrations.RemoveField(
            model_name='commentary',
            name='commentary_on',
        ),
        migrations.RemoveField(
            model_name='commentary',
            name='commentary_type',
        ),
        migrations.RemoveField(
            model_name='commentary',
            name='commentator',
        ),
        migrations.RemoveField(
            model_name='manuscriptcontent',
            name='content',
        ),
        migrations.RemoveField(
            model_name='manuscriptcontent',
            name='manuscript',
        ),
        migrations.RemoveField(
            model_name='manuscript',
            name='notes',
        ),
        migrations.CreateModel(
            name='AuthorityText2',
            fields=[
                ('basetext_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='manuscripts.BaseText')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manuscripts.Authority')),
                ('translator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translator', to='manuscripts.Translator')),
            ],
            bases=('manuscripts.basetext',),
        ),
        migrations.CreateModel(
            name='Commentary2',
            fields=[
                ('basetext_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='manuscripts.BaseText')),
                ('authorship', models.CharField(blank=True, choices=[('certain', 'Certain'), ('possible', 'Possible'), ('disputed', 'Disputed'), ('dubious', 'Dubious'), ('untrue', 'Untrue')], max_length=10, null=True)),
                ('incipit', models.TextField(blank=True, max_length=1020, null=True)),
                ('explicit', models.TextField(blank=True, max_length=1020, null=True)),
                ('mora_reference', models.CharField(blank=True, max_length=20, null=True)),
                ('commentary_on', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manuscripts.AuthorityText2')),
                ('commentary_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manuscripts.CommentaryType')),
                ('commentator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manuscripts.Commentator')),
            ],
            bases=('manuscripts.basetext',),
        ),
        migrations.DeleteModel(
            name='AuthorityText',
        ),
        migrations.DeleteModel(
            name='Commentary',
        ),
        migrations.DeleteModel(
            name='ManuscriptContent',
        ),
        migrations.AddField(
            model_name='manuscriptcontent2',
            name='content',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manuscripts.BaseText'),
        ),
        migrations.AddField(
            model_name='manuscriptcontent2',
            name='manuscript',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manuscripts.Manuscript'),
        ),
    ]
