# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-06 10:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('manuscripts', '0069_auto_20160105_2215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manuscript',
            name='notes',
        ),
        migrations.AddField(
            model_name='manuscript',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content_type', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='manuscript',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
