# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-06 15:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0070_auto_20160106_1621'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AuthorityText2',
            new_name='AuthorityText',
        ),
        migrations.RenameModel(
            old_name='Commentary2',
            new_name='Commentary',
        ),
        migrations.RenameModel(
            old_name='ManuscriptContent2',
            new_name='ManuscriptContent',
        ),
    ]
