# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-06 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0071_auto_20160106_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentary',
            name='after',
            field=models.CharField(blank=True, max_length=55, null=True, verbose_name='After date (earliest)'),
        ),
        migrations.AddField(
            model_name='commentary',
            name='before',
            field=models.CharField(blank=True, max_length=55, null=True, verbose_name='Before date (latest)'),
        ),
    ]
