# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-06 15:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0071_auto_20160106_1636'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AuthorityText',
            new_name='AuthorityText_backup',
        ),
        migrations.RenameModel(
            old_name='Commentary',
            new_name='Commentary_backup',
        ),
        migrations.RenameModel(
            old_name='ManuscriptContent',
            new_name='ManuscriptContent_backup',
        ),
    ]
