# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-07 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0074_auto_20160107_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='manuscript',
            name='annotation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manuscript',
            name='script',
            field=models.TextField(blank=True, null=True),
        ),
    ]
