# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-07 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0075_auto_20160107_1223'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='town',
            options={'ordering': ['town_name']},
        ),
    ]
