# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-07 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0076_auto_20160107_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='manuscript',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
