# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-08 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0077_manuscript_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentary',
            name='relevance',
            field=models.CharField(blank=True, choices=[('high', 'High'), ('mid', 'Some'), ('low', 'Low'), ('none', 'None')], max_length=20, null=True),
        ),
    ]
