# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-08 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0079_auto_20160108_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentary',
            name='relevance',
            field=models.IntegerField(blank=True, choices=[(3, 'High'), (2, 'Some'), (1, 'Low'), (0, 'None')], default=0, null=True),
        ),
    ]
