# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-08 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0080_auto_20160108_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentary',
            name='relevance',
            field=models.IntegerField(blank=True, choices=[(1, 'High'), (2, 'Some'), (3, 'Low'), (4, 'None')], default=4, null=True),
        ),
    ]
