# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-18 15:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0081_auto_20160108_1034'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentatorAlternative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('commentary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manuscripts.Commentary')),
                ('commentator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manuscripts.Commentator')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
