# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-18 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0082_commentatoralternative'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentatoralternative',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
