# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-19 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0083_auto_20160118_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentary',
            name='related_commentaries',
            field=models.ManyToManyField(blank=True, related_name='_commentary_related_commentaries_+', to='manuscripts.Commentary'),
        ),
    ]
