# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-19 11:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0084_commentary_related_commentaries'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentary',
            options={'ordering': ['commentator', 'title', 'modified'], 'verbose_name': 'Commentary', 'verbose_name_plural': 'Commentaries'},
        )
    ]
