# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-19 11:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0085_auto_20160119_1224'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manuscript',
            options={'ordering': ['town', 'library', 'shelfmark', 'number']},
        ),
    ]
