# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-20 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0088_auto_20160120_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentary',
            name='relevance',
            field=models.IntegerField(blank=True, choices=[(1, 'High'), (2, 'Some'), (3, 'Low'), (4, 'Unknown'), (5, 'None')], default=4, null=True),
        ),
    ]
