# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-20 21:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0089_auto_20160120_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manuscriptinspection',
            name='inspector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
