# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-21 07:10
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0090_auto_20160120_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='town',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='country', chained_model_field='country', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='archive_town', to='manuscripts.Town'),
        ),
        migrations.AlterField(
            model_name='library',
            name='library_town',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='library_country', chained_model_field='country', on_delete=django.db.models.deletion.CASCADE, related_name='library_town', to='manuscripts.Town'),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='library',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='town', chained_model_field='library_town', on_delete=django.db.models.deletion.CASCADE, related_name='library', to='manuscripts.Library'),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='town',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='country', chained_model_field='country', on_delete=django.db.models.deletion.CASCADE, related_name='town', to='manuscripts.Town'),
        ),
        migrations.AlterUniqueTogether(
            name='manuscript',
            unique_together=set([('country', 'town', 'library', 'shelfmark', 'number')]),
        ),
    ]
