# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-21 07:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0092_basetext_saeculo'),
    ]

    operations = [
        migrations.AddField(
            model_name='manuscript',
            name='saeculo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
