# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-02 13:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0093_manuscript_saeculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manuscriptcontent',
            name='content',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manuscripts.Commentary'),
        ),
    ]
