# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-02 13:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0094_auto_20160202_1407'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ManuscriptContent',
            new_name='ManuscriptContentCommentary',
        ),
    ]
