# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-05 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0095_auto_20160202_1439'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manuscriptcontentcommentary',
            options={'verbose_name': 'Manuscript content (commentary)', 'verbose_name_plural': 'Manuscript content (commentaries)'},
        ),
        migrations.AddField(
            model_name='manuscript',
            name='origin',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='folios',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='manuscriptcontentcommentary',
            name='folios',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='manuscriptcontentcommentary',
            name='note',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
