# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-05 14:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0096_auto_20160205_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manuscript',
            name='origin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='origin', to='manuscripts.Country'),
        ),
    ]
