# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-05 14:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0097_auto_20160205_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManuscriptOrigin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('origin_country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manuscripts.Country')),
                ('origin_town', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='origin_country', chained_model_field='country', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='origin_town', to='manuscripts.Town')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='origin', to='manuscripts.ManuscriptOrigin'),
        ),
    ]
