# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-16 07:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0100_library_library_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentaryEdition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('note', models.CharField(blank=True, max_length=500, null=True)),
                ('commentary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manuscripts.Commentary')),
            ],
            options={
                'verbose_name': 'Commentary edition',
                'verbose_name_plural': 'Commentary editions',
            },
        ),
    ]
