# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-15 08:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0100_library_library_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentaryEdition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('note', models.CharField(blank=True, max_length=500, null=True)),
                ('commentary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manuscripts.Commentary')),
            ],
            options={
                'verbose_name_plural': 'Commentary editions',
                'verbose_name': 'Commentary edition',
            },
        ),
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('BK', 'Book'), ('EJL', 'Electronic Journal'), ('JL', 'Journal'), ('WB', 'Website')], default='BK', max_length=3)),
                ('slug', models.CharField(max_length=128, unique=True)),
                ('author', models.CharField(max_length=512)),
                ('title', models.CharField(max_length=512)),
                ('year', models.IntegerField(default=2000)),
                ('series', models.CharField(blank=True, max_length=512, null=True)),
                ('volume', models.IntegerField(blank=True, null=True)),
                ('edition', models.IntegerField(blank=True, null=True)),
                ('isbn', models.CharField(blank=True, max_length=17, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('publisher', models.CharField(blank=True, max_length=128, null=True)),
                ('place', models.CharField(blank=True, max_length=128, null=True)),
                ('abstract', models.TextField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('keywords', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='commentaryedition',
            name='edition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manuscripts.Edition'),
        ),
    ]
