# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-16 07:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0101_commentaryedition'),
        ('references', '0002_auto_20160216_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentaryedition',
            name='edition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='references.TextEdition'),
        ),
    ]
