# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-15 09:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0101_auto_20160215_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentaryedition',
            name='edition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='references.Edition'),
        ),
        migrations.DeleteModel(
            name='Edition',
        ),
    ]
