# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-16 10:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0102_commentaryedition_edition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authoritytext',
            name='author',
        ),
        migrations.RemoveField(
            model_name='authoritytext',
            name='basetext_ptr',
        ),
        migrations.RemoveField(
            model_name='authoritytext',
            name='translator',
        ),
        migrations.RemoveField(
            model_name='commentary',
            name='basetext_ptr',
        ),
        migrations.RemoveField(
            model_name='commentary',
            name='commentary_on',
        ),
        migrations.RemoveField(
            model_name='commentary',
            name='commentary_type',
        ),
        migrations.RemoveField(
            model_name='commentary',
            name='commentator',
        ),
        migrations.RemoveField(
            model_name='commentary',
            name='related_commentaries',
        ),
        migrations.RemoveField(
            model_name='commentaryedition',
            name='commentary',
        ),
        migrations.RemoveField(
            model_name='commentaryedition',
            name='edition',
        ),
        migrations.RemoveField(
            model_name='commentatoralternative',
            name='commentary',
        ),
        migrations.RemoveField(
            model_name='commentatoralternative',
            name='commentator',
        ),
        migrations.AlterField(
            model_name='manuscriptcontentcommentary',
            name='content',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='commentaries.Commentary'),
        ),
        migrations.DeleteModel(
            name='Authority',
        ),
        migrations.DeleteModel(
            name='AuthorityText',
        ),
        migrations.DeleteModel(
            name='BaseText',
        ),
        migrations.DeleteModel(
            name='Commentary',
        ),
        migrations.DeleteModel(
            name='CommentaryEdition',
        ),
        migrations.DeleteModel(
            name='CommentaryType',
        ),
        migrations.DeleteModel(
            name='Commentator',
        ),
        migrations.DeleteModel(
            name='CommentatorAlternative',
        ),
        migrations.DeleteModel(
            name='Translator',
        ),
    ]
