# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-16 11:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('manuscripts', '0103_auto_20160216_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archive',
            name='country',
        ),
        migrations.RemoveField(
            model_name='archive',
            name='town',
        ),
        migrations.RemoveField(
            model_name='library',
            name='library_country',
        ),
        migrations.RemoveField(
            model_name='library',
            name='library_town',
        ),
        migrations.RemoveField(
            model_name='town',
            name='country',
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='places.Country'),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='library',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='town', chained_model_field='library_town', on_delete=django.db.models.deletion.CASCADE, related_name='library', to='places.Library'),
        ),
        migrations.AlterField(
            model_name='manuscript',
            name='town',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='country', chained_model_field='country', on_delete=django.db.models.deletion.CASCADE, related_name='town', to='places.Town'),
        ),
        migrations.AlterField(
            model_name='manuscriptorigin',
            name='origin_country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='places.Country'),
        ),
        migrations.AlterField(
            model_name='manuscriptorigin',
            name='origin_town',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='origin_country', chained_model_field='country', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='origin_town', to='places.Town'),
        ),
        migrations.AlterField(
            model_name='reproduction',
            name='archive',
            field=models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to='repositories.Archive'),
        ),
        migrations.DeleteModel(
            name='Archive',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Library',
        ),
        migrations.DeleteModel(
            name='Town',
        ),
    ]
