# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-01 07:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_markdown.models


class Migration(migrations.Migration):

    replaces = [('commentaries', '0001_squashed_0008_auto_20160403_1953'), ('commentaries', '0002_text'), ('commentaries', '0003_auto_20160415_2023'), ('commentaries', '0004_auto_20160415_2046'), ('commentaries', '0005_auto_20160415_2052'), ('commentaries', '0006_auto_20160415_2054'), ('commentaries', '0007_auto_20160415_2137'), ('commentaries', '0008_remove_texttype_related_text'), ('commentaries', '0009_auto_20160415_2149'), ('commentaries', '0010_auto_20160415_2150'), ('commentaries', '0011_auto_20160415_2216'), ('commentaries', '0012_delete_texttype'), ('commentaries', '0013_auto_20160415_2239'), ('commentaries', '0014_auto_20160415_2303'), ('commentaries', '0015_auto_20160601_0937')]

    initial = True

    dependencies = [
        ('persons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Authority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('birth', models.CharField(blank=True, max_length=50, null=True)),
                ('death', models.CharField(blank=True, max_length=50, null=True)),
                ('floruit', models.CharField(blank=True, max_length=50, null=True)),
                ('note', django_markdown.models.MarkdownField(blank=True, null=True)),
                ('literature', django_markdown.models.MarkdownField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Authorities',
            },
        ),
        migrations.CreateModel(
            name='BaseText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=500)),
                ('title_addon', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title addon')),
                ('date', models.CharField(blank=True, max_length=50, null=True)),
                ('saeculo', models.CharField(blank=True, max_length=50, null=True)),
                ('note', django_markdown.models.MarkdownField(blank=True, null=True)),
                ('literature', django_markdown.models.MarkdownField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CommentaryEdition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('note', models.CharField(blank=True, max_length=500, null=True)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='references.TextEdition')),
                ('commentary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commentaries.Commentary')),
            ],
            options={
                'verbose_name_plural': 'Commentary editions',
                'verbose_name': 'Commentary edition',
            },
        ),
        migrations.CreateModel(
            name='CommentaryType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('commentary_type', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Commentator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('birth', models.CharField(blank=True, max_length=50, null=True)),
                ('death', models.CharField(blank=True, max_length=50, null=True)),
                ('floruit', models.CharField(blank=True, max_length=50, null=True)),
                ('note', django_markdown.models.MarkdownField(blank=True, null=True)),
                ('literature', django_markdown.models.MarkdownField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AuthorAlternative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persons.Commentator')),
                ('commentary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commentaries.Text')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Translator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('birth', models.CharField(blank=True, max_length=50, null=True)),
                ('death', models.CharField(blank=True, max_length=50, null=True)),
                ('floruit', models.CharField(blank=True, max_length=50, null=True)),
                ('note', django_markdown.models.MarkdownField(blank=True, null=True)),
                ('literature', django_markdown.models.MarkdownField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AuthorityText',
            fields=[
                ('basetext_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='commentaries.BaseText')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persons.Authority')),
                ('translator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translator', to='persons.Translator')),
            ],
            options={
                'ordering': ['author'],
            },
            bases=('commentaries.basetext',),
        ),
        migrations.DeleteModel(
            name='Authority',
        ),
        migrations.DeleteModel(
            name='Commentator',
        ),
        migrations.DeleteModel(
            name='Translator',
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=500)),
                ('title_addon', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title addon')),
                ('date', models.CharField(blank=True, max_length=50, null=True)),
                ('saeculo', models.CharField(blank=True, max_length=50, null=True)),
                ('note', django_markdown.models.MarkdownField(blank=True, null=True)),
                ('literature', django_markdown.models.MarkdownField(blank=True, null=True)),
                ('authorship', models.CharField(blank=True, choices=[('certain', 'Certain'), ('possible', 'Possible'), ('disputed', 'Disputed'), ('dubious', 'Dubious'), ('untrue', 'Untrue')], max_length=10, null=True)),
                ('after', models.CharField(blank=True, max_length=55, null=True, verbose_name='After date (earliest)')),
                ('before', models.CharField(blank=True, max_length=55, null=True, verbose_name='Before date (latest)')),
                ('incipit', models.TextField(blank=True, max_length=1020, null=True)),
                ('explicit', models.TextField(blank=True, max_length=1020, null=True)),
                ('mora_reference', models.CharField(blank=True, max_length=20, null=True)),
                ('relevance', models.IntegerField(blank=True, choices=[(1, 'High'), (2, 'Some'), (3, 'Low'), (4, 'Unknown'), (5, 'None')], default=4, null=True)),
                ('edition_coverage', models.IntegerField(blank=True, choices=[(0, 'None'), (1, 'Partial'), (2, 'Full')], default=0)),
                ('commentary_on', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commentaries.AuthorityText')),
                ('commentary_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commentaries.CommentaryType')),
                ('commentator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persons.Commentator')),
                ('related_commentaries', models.ManyToManyField(blank=True, related_name='_text_related_commentaries_+', to='commentaries.Text')),
            ],
            options={
                'ordering': ['commentator', 'title', 'modified'],
                'verbose_name': 'Commentary',
                'verbose_name_plural': 'Commentaries',
            },
        ),
        migrations.AlterModelOptions(
            name='commentaryedition',
            options={'verbose_name': 'Text edition', 'verbose_name_plural': 'Text editions'},
        ),
        migrations.AlterModelOptions(
            name='text',
            options={'ordering': ['commentator', 'title', 'modified'], 'verbose_name': 'Text', 'verbose_name_plural': 'Texts'},
        ),
        migrations.RemoveField(
            model_name='commentaryedition',
            name='commentary',
        ),
        migrations.AlterModelOptions(
            name='text',
            options={'ordering': ['author', 'title', 'modified'], 'verbose_name': 'Text', 'verbose_name_plural': 'Texts'},
        ),
        migrations.RenameField(
            model_name='text',
            old_name='commentator',
            new_name='author',
        ),
        migrations.AddField(
            model_name='text',
            name='text_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='text',
            name='commentary_on',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commentaries.Text'),
        ),
        migrations.RemoveField(
            model_name='authoritytext',
            name='author',
        ),
        migrations.RemoveField(
            model_name='authoritytext',
            name='basetext_ptr',
        ),
        migrations.RemoveField(
            model_name='authoritytext',
            name='translator',
        ),
        migrations.DeleteModel(
            name='AuthorityText',
        ),
        migrations.DeleteModel(
            name='BaseText',
        ),
        migrations.RemoveField(
            model_name='commentaryedition',
            name='edition',
        ),
        migrations.DeleteModel(
            name='CommentaryEdition',
        ),
    ]
