# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-15 18:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_markdown.models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0001_initial'),
        ('commentaries', '0001_squashed_0008_auto_20160403_1953'),
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=500)),
                ('title_addon', models.CharField(blank=True, max_length=255, null=True, verbose_name='Title addon')),
                ('date', models.CharField(blank=True, max_length=50, null=True)),
                ('saeculo', models.CharField(blank=True, max_length=50, null=True)),
                ('note', django_markdown.models.MarkdownField(blank=True, null=True)),
                ('literature', django_markdown.models.MarkdownField(blank=True, null=True)),
                ('authorship', models.CharField(blank=True, choices=[('certain', 'Certain'), ('possible', 'Possible'), ('disputed', 'Disputed'), ('dubious', 'Dubious'), ('untrue', 'Untrue')], max_length=10, null=True)),
                ('after', models.CharField(blank=True, max_length=55, null=True, verbose_name='After date (earliest)')),
                ('before', models.CharField(blank=True, max_length=55, null=True, verbose_name='Before date (latest)')),
                ('incipit', models.TextField(blank=True, max_length=1020, null=True)),
                ('explicit', models.TextField(blank=True, max_length=1020, null=True)),
                ('mora_reference', models.CharField(blank=True, max_length=20, null=True)),
                ('relevance', models.IntegerField(blank=True, choices=[(1, 'High'), (2, 'Some'), (3, 'Low'), (4, 'Unknown'), (5, 'None')], default=4, null=True)),
                ('edition_coverage', models.IntegerField(blank=True, choices=[(0, 'None'), (1, 'Partial'), (2, 'Full')], default=0)),
                ('commentary_on', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commentaries.AuthorityText')),
                ('commentary_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commentaries.CommentaryType')),
                ('commentator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persons.Commentator')),
                ('related_commentaries', models.ManyToManyField(blank=True, related_name='_text_related_commentaries_+', to='commentaries.Text')),
            ],
            options={
                'verbose_name': 'Commentary',
                'ordering': ['commentator', 'title', 'modified'],
                'verbose_name_plural': 'Commentaries',
            },
        ),
    ]
