# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-20 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commentaries', '0001_squashed_0015_auto_20160601_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='edition_coverage',
            field=models.IntegerField(blank=True, choices=[(0, 'None'), (1, 'Partial'), (2, 'Full'), (3, 'Early print')], default=0),
        ),
    ]
