# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-15 18:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commentaries', '0002_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentaryedition',
            options={'verbose_name': 'Text edition', 'verbose_name_plural': 'Text editions'},
        ),
        migrations.AlterModelOptions(
            name='text',
            options={'ordering': ['commentator', 'title', 'modified'], 'verbose_name': 'Text', 'verbose_name_plural': 'Texts'},
        ),
        migrations.AlterField(
            model_name='commentaryedition',
            name='commentary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commentaries.Text'),
        ),
        migrations.AlterField(
            model_name='commentatoralternative',
            name='commentary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commentaries.Text'),
        ),
    ]
