# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-15 18:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commentaries', '0003_auto_20160415_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentary',
            name='basetext_ptr',
        ),
        migrations.RemoveField(
            model_name='commentary',
            name='commentary_on',
        ),
        migrations.RemoveField(
            model_name='commentary',
            name='commentary_type',
        ),
        migrations.RemoveField(
            model_name='commentary',
            name='commentator',
        ),
        migrations.RemoveField(
            model_name='commentary',
            name='related_commentaries',
        ),
        migrations.DeleteModel(
            name='Commentary',
        ),
    ]
