# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-21 08:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commentaries', '0004_auto_20160621_1032'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Upload',
            new_name='TextUpload',
        ),
    ]
