# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-01 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commentaries', '0004_auto_20160329_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentaryedition',
            name='coverage',
            field=models.CharField(blank=True, choices=[(0, 'None'), (1, 'Partial'), (2, 'Complete')], max_length=10, null=True),
        ),
    ]
