# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-15 18:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commentaries', '0004_auto_20160415_2046'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='text',
            options={'ordering': ['author', 'title', 'modified'], 'verbose_name': 'Text', 'verbose_name_plural': 'Texts'},
        ),
        migrations.RenameField(
            model_name='text',
            old_name='commentator',
            new_name='author',
        ),
    ]
