# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-01 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commentaries', '0005_commentaryedition_coverage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentaryedition',
            name='coverage',
        ),
        migrations.AddField(
            model_name='commentary',
            name='edition_coverage',
            field=models.IntegerField(blank=True, choices=[(0, 'None'), (1, 'Partial'), (2, 'Complete')], default=0, null=True),
        ),
    ]
