# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-15 18:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commentaries', '0005_auto_20160415_2052'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommentatorAlternative',
            new_name='AuthorAlternative',
        ),
        migrations.RenameField(
            model_name='authoralternative',
            old_name='commentator',
            new_name='author',
        ),
    ]
