# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-15 19:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commentaries', '0006_auto_20160415_2054'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('related_text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commentaries.Text')),
            ],
        ),
        migrations.AddField(
            model_name='text',
            name='text_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commentaries.TextType'),
        ),
    ]
