# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-15 19:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commentaries', '0008_remove_texttype_related_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='text_type',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='commentaries.TextType'),
        ),
    ]
