# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-15 19:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commentaries', '0009_auto_20160415_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='text_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commentaries.TextType'),
        ),
    ]
