# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-15 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commentaries', '0010_auto_20160415_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='text_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
