# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-15 20:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commentaries', '0012_delete_texttype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='commentary_on',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commentaries.Text'),
        ),
    ]
