# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-15 21:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commentaries', '0013_auto_20160415_2239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authoritytext',
            name='author',
        ),
        migrations.RemoveField(
            model_name='authoritytext',
            name='basetext_ptr',
        ),
        migrations.RemoveField(
            model_name='authoritytext',
            name='translator',
        ),
        migrations.DeleteModel(
            name='AuthorityText',
        ),
        migrations.DeleteModel(
            name='BaseText',
        ),
    ]
