# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-01 07:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commentaries', '0014_auto_20160415_2303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentaryedition',
            name='commentary',
        ),
        migrations.RemoveField(
            model_name='commentaryedition',
            name='edition',
        ),
        migrations.DeleteModel(
            name='CommentaryEdition',
        ),
    ]
