# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-16 07:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('citations', '__first__'),
        ('references', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextEdition',
            fields=[
                ('reference_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='citations.Reference')),
            ],
            bases=('citations.reference',),
        ),
        migrations.DeleteModel(
            name='Edition',
        ),
    ]
